services:
  aktivistisch:
    command: "/app/entrypoint.sh"
    build: .
    volumes:
      - static:/app/static
      - media:/app/media
    environment:
      MYSQL_DATABASE: 'aktivistisch'
      MYSQL_USER: 'aktivistisch'
      MYSQL_PASSWORD: 'aktivistisch'
      MYSQL_HOST: 'aktivistisch_db'
      MYSQL_PORT: '3306'
      PRODUCTION: 'TRUE'
    links:
      - aktivistisch_db
    networks:
      - intern
    depends_on:
      - aktivistisch_db

  aktivistisch_db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: aktivistisch
      MYSQL_DATABASE: aktivistisch
      MYSQL_USER: aktivistisch
      MYSQL_PASSWORD: aktivistisch
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - intern
  
  aktivistisch_proxy:
    build: ./proxy
    volumes:
      - media:/app/media
      - static:/app/static
      - cache:/app/cache

    depends_on:
      - aktivistisch  
    networks:
      - extern
      - intern

networks:
  extern:
    name: general
    external: true
  intern:
    driver: bridge

volumes:
  static:
  media:
  mysql:
  cache: