services:
  aktivistisch:
    command: "/app/entrypoint.sh"
    build: .
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    environment:
      MYSQL_DATABASE: 'aktivistisch'
      MYSQL_USER: 'aktivistisch'
      MYSQL_PASSWORD: 'aktivistisch'
      MYSQL_HOST: 'aktivistisch_db'
      MYSQL_PORT: '3306'
      PRODUCTION: 'TRUE'
    links:
      - aktivistisch_db
    networks:
      - extern
      - intern

      
  aktivistisch_db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: aktivistisch
      MYSQL_DATABASE: aktivistisch
      MYSQL_USER: aktivistisch
      MYSQL_PASSWORD: aktivistisch
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - intern

networks:
  extern:
    name: general
    external: true
  intern:
    driver: bridge

