# Generated by Django 5.0 on 2023-12-16 20:24

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=50)),
                ('featured', models.BooleanField(default=False)),
                ('experience_level', models.IntegerField()),
                ('experience_note', models.CharField(max_length=100)),
                ('effort_level', models.IntegerField()),
                ('effort_note', models.CharField(max_length=100)),
                ('min_required_people', models.IntegerField()),
                ('max_required_people', models.IntegerField(null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('example', ckeditor.fields.RichTextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.projectidea')),
            ],
        ),
    ]
