# Generated by Django 5.0 on 2023-12-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_step_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectidea',
            name='effort_note',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projectidea',
            name='experience_note',
            field=models.TextField(max_length=100),
        ),
    ]
