# Generated by Django 5.0 on 2023-12-18 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_alter_projectidea_effort_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='catalogue.projectidea'),
        ),
    ]
