# Generated by Django 5.0 on 2023-12-18 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_alter_step_idea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='idea',
            new_name='project_idea',
        ),
    ]
