# Generated by Django 5.0 on 2023-12-23 14:56

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_projectidea_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('attachment_type', models.CharField(choices=[('RESSOURCE', 'Ressource'), ('DOWNLOAD', 'Download'), ('TEMPLATE', 'Template')], default='RESSOURCE', max_length=9)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='attachments')),
                ('project_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='catalogue.projectidea')),
            ],
        ),
    ]
