# Generated by Django 5.0 on 2023-12-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment_type',
            field=models.CharField(choices=[('RESSOURCE', 'Ressource'), ('DOWNLOAD', 'Download')], default='RESSOURCE', max_length=9),
        ),
    ]
