# Generated by Django 5.0 on 2023-12-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_alter_attachment_attachment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectidea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
