# Generated by Django 5.0 on 2023-12-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_alter_attachment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment_type',
            field=models.CharField(choices=[('RESOURCE', 'Resource'), ('DOWNLOAD', 'Download')], default='RESOURCE', max_length=9),
        ),
    ]
