# Generated by Django 5.0 on 2023-12-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_alter_attachment_attachment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectidea',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
