# Generated by Django 5.0 on 2023-12-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_alter_projectidea_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectidea',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
