# Generated by Django 5.0 on 2023-12-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_faq_overviewconfiguration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overviewconfiguration',
            old_name='text',
            new_name='overview_text',
        ),
        migrations.AddField(
            model_name='overviewconfiguration',
            name='page_description',
            field=models.CharField(default='page_description', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overviewconfiguration',
            name='page_title',
            field=models.CharField(default='page_title', max_length=100),
            preserve_default=False,
        ),
    ]
