# Generated by Django 5.0 on 2023-12-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_rename_text_overviewconfiguration_overview_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overviewconfiguration',
            name='page_description',
            field=models.TextField(max_length=500),
        ),
    ]
