# Generated by Django 5.0 on 2024-01-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_alter_overviewconfiguration_page_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectidea',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
