# Generated by Django 5.0 on 2024-01-23 16:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_remove_projectidea_effort_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overviewconfiguration',
            name='impressum_text',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
