# Generated by Django 5.0 on 2024-01-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_overviewconfiguration_impressum_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
