# Generated by Django 5.0 on 2024-02-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_party_prediction_and_more_squashed_0032_remove_prediction_last_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['order_by'], 'verbose_name_plural': 'Parties'},
        ),
        migrations.AddField(
            model_name='party',
            name='border',
            field=models.BooleanField(default=False),
        ),
    ]
